spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    enabled: true
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_USERNAME}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

debug: true